words = [
    "abbrs",
    "alsa",
    "calt",
    "clicolor",
    "crun",
    "cwd",
    "direnv",
    "dlig",
    "dns",
    "eza",
    "fontconfig",
    "fzf",
    "ghostty",
    "librewolf",
    "liga",
    "networkmanager",
    "nixos",
    "nixosvm",
    "nixpkgs",
    "optimise",
    "pipewire",
    "pkgs",
    "podman",
    "polkit",
    "rtkit",
    "runu",
    "systemd",
    "unrar",
    "virtualisation",
    "wireplumber",
    "xdg",
    "yazi",
    "zoxide",
    "zram",
]
